import { z } from 'zod';
import { ItemStateEnum, LegalStatusEnum } from '../enums/item';
export declare const itemSchema: z.ZodObject<{
    id: z.ZodString;
    is_deleted: z.ZodNullable<z.ZodOptional<z.ZodBoolean>>;
    createdAt: z.ZodNullable<z.ZodOptional<z.ZodDate>>;
    updatedAt: z.ZodNullable<z.ZodOptional<z.ZodDate>>;
    deletedAt: z.ZodNullable<z.ZodOptional<z.ZodDate>>;
    plate: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    brand: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    model: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    year: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    version: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    photos: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    docs: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    kilometraje: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    legal_status: z.ZodOptional<z.ZodNullable<z.ZodEnum<typeof LegalStatusEnum>>>;
    state: z.ZodDefault<z.ZodEnum<typeof ItemStateEnum>>;
}, z.core.$strict>;
export type ItemDto = z.infer<typeof itemSchema>;
